INSERT INTO "Faq" (id, question, answer, "order", "createdAt") VALUES
('faq1', 'Apa itu Exha Wave?', 'Exha Wave adalah SMM Panel Indonesia yang menyediakan jasa buzzer, like, view, follower, comment, share, save untuk TikTok, Instagram, Facebook, YouTube, dan lainnya. Kami membantu meningkatkan engagement media sosial Anda dengan cepat dan aman.', 1, NOW()),
('faq2', 'Apakah layanan Exha Wave aman?', 'Ya, semua layanan kami menggunakan metode yang aman dan sesuai dengan ketentuan platform. Kami menggunakan akun real dan aktif untuk memastikan hasil yang berkualitas tanpa risiko.', 2, NOW()),
('faq3', 'Berapa lama proses pesanan?', 'Proses pesanan bervariasi tergantung jenis layanan. Namun, sebagian besar pesanan mulai diproses dalam hitungan menit setelah pembayaran dikonfirmasi.', 3, NOW()),
('faq4', 'Bagaimana cara melakukan pemesanan?', '1. Pilih platform dan layanan di halaman Layanan Kami\n2. Isi link target dan jumlah yang diinginkan\n3. Tambahkan ke keranjang\n4. Checkout dan pilih metode pembayaran\n5. Lakukan pembayaran', 4, NOW()),
('faq5', 'Apa itu Exha Points?', 'Exha Points adalah poin loyalitas yang bisa Anda dapatkan dari login harian, referral, dan spin wheel. Setiap 100 poin setara dengan Rp10 yang bisa digunakan sebagai potongan belanja.', 5, NOW()),
('faq6', 'Bagaimana cara top up saldo?', 'Anda bisa top up saldo Exha melalui halaman Topup. Pilih nominal, klik Topup, dan selesaikan pembayaran melalui Midtrans. Saldo akan otomatis bertambah setelah pembayaran sukses.', 6, NOW()),
('faq7', 'Apakah ada minimal order?', 'Ya, setiap layanan memiliki minimal order yang berbeda-beda. Anda bisa melihat minimal order di halaman detail layanan sebelum memesan.', 7, NOW()),
('faq8', 'Bagaimana cara mendapatkan Exha Points?', 'Exha Points bisa didapatkan dari:\n- Login harian (+10 poin)\n- Spin Wheel harian\n- Mengajak teman dengan kode referral (+50 poin)\n- Bonus dari admin', 8, NOW()),
('faq9', 'Apa itu jasa buzzer Exha Wave?', 'Jasa buzzer Exha Wave adalah layanan untuk meningkatkan engagement media sosial Anda secara instan. Kami menyediakan buzzer Indonesia asli untuk like, view, follower, comment, share, dan save di berbagai platform.', 9, NOW()),
('faq10', 'Apakah bisa refund jika pesanan gagal?', 'Jika pesanan tidak dapat diproses karena kendala teknis, dana Anda akan dikembalikan ke Saldo Exha. Silakan hubungi admin untuk bantuan lebih lanjut.', 10, NOW());
